[env]
platform = atmelmegaavr
board = ATtiny412
framework = arduino
board_build.f_cpu = 5000000L
upload_protocol = serialupdi
#extra_scripts = pre:set_eesave.py

[env:NTC]
build_flags = -DUSE_NTC

[env:DS18B20]
build_flags = -DUSE_DS18B20

[env:plain]
